/* Cookie Cloud Landing Page
 * Implements a refined, dark-first landing experience with
 * Hero, Feature grid, CTA, Footer, extension dropdown and i18n toggle.
 */
import { useState } from 'react'

// Simple i18n dictionary for EN/ZH. Comments in English as requested.
const dict = {
  en: {
    nav: { github: 'GitHub', docs: 'Docs', agent: 'AI Agent', get: 'Get Extension', lang: '中文' },
    hero: {
      h1a: 'Sync your cookies',
      h1b: 'across browsers & devices',
      p: 'Cookie Cloud keeps your session cookies in sync — fast, privacy-first, and developer-friendly. Perfect for testing, automation, and multi-device workflows.',
      get: 'Get the Extension',
      self: 'Self-host',
      edge: 'Edge Add-on',
      chrome: 'Chrome Web Store',
    },
    features: [
      { title: 'Configure once', desc: 'Automatic cookie sync after a one-time setup. No manual export/import.' },
      { title: 'Privacy-first', desc: 'Your data stays under your control. Self-host with your own infrastructure.' },
      { title: 'End-to-end encrypted', desc: 'Client-side encryption ensures only you can read your cookie data.' },
      { title: 'Cross-browser', desc: 'Works across Chromium-based browsers and beyond via extension.' },
      { title: 'Automation-friendly', desc: 'Useful in QA flows, playwright tests, and developer tooling.' },
    ],
    skill: {
      badge: 'FOR AI AGENTS',
      h2: 'Give your AI agent cookie superpowers',
      p: 'Copy the skill below and paste it into any AI agent — Claude, ChatGPT, Cursor, DeepSeek and more. The agent will configure itself, then fetch, decrypt and inject your Cookie Cloud session into the current project automatically.',
      steps: [
        { title: 'Copy the skill', desc: 'One click copies the full protocol, decryption spec and integration guide.' },
        { title: 'Paste into your agent', desc: 'Works with Claude, ChatGPT, Cursor, DeepSeek and any capable coding agent.' },
        { title: 'Agent implements sync', desc: 'It asks for Host / UUID / Password (or reads your env vars) and wires cookie sync into your project.' },
      ],
      copy: 'Copy skill',
      copied: 'Copied ✓',
      envNote: 'Configure your extension once — then let any agent do the rest.',
      install: 'Or install it directly as an agent skill:',
      copyCmd: 'Copy command',
      copiedCmd: 'Copied ✓',
      skillFile: 'View SKILL.md source',
      text: `# CookieCloud Agent Skill — Cookie Sync

You are an agent that implements the CookieCloud protocol. CookieCloud is a tool that syncs browser cookies and LocalStorage to a (self-hosted) server with end-to-end encryption. When the user asks you to sync cookies, restore a logged-in session, or inject session cookies into their current project, follow this spec.

## 1. Configuration — ask first, or read env
Three values are needed:
- COOKIE_CLOUD_HOST — server URL, e.g. https://ccc.ft07.com or self-hosted http://127.0.0.1:8088 (strip any trailing slash)
- COOKIE_CLOUD_UUID — UUID generated by the browser extension
- COOKIE_CLOUD_PASSWORD — encryption password

If environment variables with exactly these names already exist, use them. Otherwise ask the user for all three. Never guess or invent values.

## 2. Download the ciphertext
GET {HOST}/get/{UUID}
Response JSON: { "encrypted": "...", "crypto_type": "legacy" | "aes-128-cbc-fixed" }

## 3. Decrypt (locally, always)
Key material is the first 16 characters of the MD5(UUID + '-' + PASSWORD) hex digest.
- "legacy" (old default format): equivalent to CryptoJS.AES.decrypt(encrypted, key) with key passed as a string passphrase — OpenSSL EVP_BytesToKey (MD5, AES-256-CBC, PKCS7) with a "Salted__" wrapper. See CryptoJS docs / the CookieCloud README.
- "aes-128-cbc-fixed" (new format, preferred): standard AES-128-CBC. key = UTF-8 bytes of the 16 hex characters above; IV fixed to 16 zero bytes (00000000000000000000000000000000); PKCS7 padding; ciphertext is raw Base64 without the "Salted__" prefix.
Prefer the crypto_type returned by the server. JSON.parse the plaintext to get:
{ "cookie_data": { "example.com": [cookie, ...], ... }, "local_storage_data": { ... } }

## 4. Apply cookies to the current project
Flatten all cookie arrays in cookie_data into one list; if cookie.sameSite === 'unspecified', set it to 'Lax'. Then inject into the project's browser context / HTTP session:
- Playwright: browser.newContext() then context.addCookies(cookies)
- Puppeteer: page.setCookie(...cookies)
- Selenium: driver.add_cookie(cookie) for each cookie
- Node fetch/undici or Python requests: build the Cookie header from the serialized cookies

## 5. Implement for the current project's stack
- Node.js: fetch + crypto-js (node:crypto also works for aes-128-cbc-fixed). Reference: CookieCloud repo, examples/playwright.
- Python: PyCookieCloud (pip install pycookiecloud) or pycryptodome; note "legacy" is the EVP_BytesToKey format.
- Go / Rust / Java / PHP: implement the algorithm above; examples/fixediv has fixed-IV references.
- If the project already has login/session code, wrap "fetch → decrypt → inject" as an init helper and wire it into the existing flow so the rest of the code runs authenticated.

## 6. Security requirements
- The server only stores ciphertext; GET /get/:uuid needs no password, decryption happens locally.
- Never hardcode UUID/PASSWORD into source or commit them. Prefer environment variables or a .env file listed in .gitignore.
- When done, briefly report: which config sources you used, which files you created or changed, and how to run and verify the sync.
`,
    },
    cta: { h2: 'Ready to streamline your cookie workflow?', p: 'Install the extension or self-host the API and start syncing today.', get: 'Get Extension', repo: 'GitHub Repo' },
    footer: { license: 'GPLv3 License' },
  },
  zh: {
    nav: { github: 'GitHub', docs: '文档', agent: 'AI Agent', get: '安装扩展', lang: 'EN' },
    hero: {
      h1a: '同步你的 Cookie',
      h1b: '跨浏览器与设备',
      p: 'Cookie Cloud 让会话 Cookie 自动同步——快速、隐私优先、开发者友好。适用于测试、自动化与多设备场景。',
      get: '安装扩展',
      self: '自托管',
      edge: 'Edge 应用商店',
      chrome: 'Chrome 应用商店',
    },
    features: [
      { title: '一次配置', desc: '一次设置后自动同步 Cookie，无需手动导入/导出。' },
      { title: '隐私优先', desc: '数据由你掌控，可在自有基础设施上自托管。' },
      { title: '端到端加密', desc: '在客户端加密，只有你可以读取 Cookie 数据。' },
      { title: '跨浏览器', desc: '支持 Chromium 系浏览器，更多浏览器可通过扩展支持。' },
      { title: '自动化友好', desc: '适用于 QA 流程、Playwright 测试与开发工具。' },
    ],
    skill: {
      badge: 'FOR AI AGENTS',
      h2: '给你的 AI Agent 加上 Cookie 同步能力',
      p: '复制下面的技能文本，粘贴给任意 AI Agent——Claude、ChatGPT、Cursor、DeepSeek 等。Agent 会自动完成配置，为你的当前项目拉取、解密并注入 CookieCloud 会话。',
      steps: [
        { title: '复制技能', desc: '一键复制完整的协议说明、解密规范与接入指引。' },
        { title: '粘贴给 Agent', desc: '适用于 Claude、ChatGPT、Cursor、DeepSeek 及各类编程 Agent。' },
        { title: 'Agent 自动实现', desc: '它会向你索取 Host / UUID / Password（或读取环境变量），并把 Cookie 同步接入你的项目。' },
      ],
      copy: '复制技能',
      copied: '已复制 ✓',
      envNote: '在扩展里配置一次，之后交给任意 Agent 完成其余工作。',
      install: '或作为 Agent 技能直接安装：',
      copyCmd: '复制命令',
      copiedCmd: '已复制 ✓',
      skillFile: '查看 SKILL.md 源文件',
      text: `# CookieCloud Agent 技能 — Cookie 同步

你是一个已实现 CookieCloud 协议的 AI Agent。CookieCloud 是一个把浏览器 Cookie 与 LocalStorage 端到端加密同步到（自建）服务器的工具。当用户要求你在其当前项目中同步 Cookie、恢复登录态或注入会话时，请严格按本规范执行。

## 1. 配置信息：先询问，或读环境变量
需要三项信息：
- COOKIE_CLOUD_HOST：服务器地址，如 https://ccc.ft07.com 或自建 http://127.0.0.1:8088（去掉末尾斜杠）
- COOKIE_CLOUD_UUID：浏览器插件生成的 UUID
- COOKIE_CLOUD_PASSWORD：加密密码

若环境中已存在与上述同名的环境变量，直接使用；否则先向用户询问这三项。不要猜测或编造。

## 2. 下载密文
GET {HOST}/get/{UUID}
返回 JSON：{ "encrypted": "...", "crypto_type": "legacy" | "aes-128-cbc-fixed" }

## 3. 解密（一律在本地进行）
密钥材料：MD5(UUID + '-' + PASSWORD) 的十六进制摘要，取前 16 个字符。
- crypto_type = legacy（旧版默认格式）：等同 CryptoJS.AES.decrypt(encrypted, key)，key 以字符串口令传入，底层是 OpenSSL EVP_BytesToKey（MD5、AES-256-CBC、PKCS7），带 "Salted__" 包装。可参考 CryptoJS 文档与 CookieCloud README。
- crypto_type = aes-128-cbc-fixed（新版，推荐）：标准 AES-128-CBC；key 为上述 16 个十六进制字符的 UTF-8 字节；IV 固定为 16 个零字节（00000000000000000000000000000000）；PKCS7 填充；密文为纯 Base64，无 "Salted__" 前缀。
优先使用服务器返回的 crypto_type。解密后 JSON.parse 得到明文：
{ "cookie_data": { "example.com": [cookie, ...], ... }, "local_storage_data": { ... } }

## 4. 把 Cookie 应用到当前项目
将 cookie_data 中所有域名的 Cookie 数组合并（cookie.sameSite === 'unspecified' 时改为 'Lax'），注入到项目的浏览器上下文 / HTTP 会话：
- Playwright：browser.newContext() 后 context.addCookies(cookies)
- Puppeteer：page.setCookie(...cookies)
- Selenium：逐个 driver.add_cookie(cookie)
- Node fetch/undici 或 Python requests：用序列化后的 Cookie 组装 Cookie 请求头

## 5. 按当前项目技术栈落地
- Node.js：fetch + crypto-js（aes-128-cbc-fixed 也可用 node:crypto）。参考 CookieCloud 仓库 examples/playwright。
- Python：可用 PyCookieCloud（pip install pycookiecloud），或按上述算法用 pycryptodome 实现（注意 legacy 是 EVP_BytesToKey 格式）。
- Go / Rust / Java / PHP：按上述算法实现，examples/fixediv 提供固定 IV 参考实现。
- 若项目已有登录/会话逻辑，把「拉取解密 → 注入」封装成初始化辅助函数并接入现有流程，让其余代码在登录态下运行。

## 6. 安全要求
- 服务器只保存密文；GET /get/:uuid 无需密码，解密一律在本地完成。
- 绝不把 UUID / PASSWORD 明文硬编码进源码或提交到仓库；优先使用环境变量或加入 .gitignore 的 .env 文件。
- 完成后简要汇报：使用了哪些配置来源、创建/修改了哪些文件、如何运行验证同步。
`,
    },
    cta: { h2: '准备好优化你的 Cookie 工作流了吗？', p: '安装扩展或自托管 API，立即开始同步。', get: '安装扩展', repo: 'GitHub 仓库' },
    footer: { license: 'GPLv3 许可' },
  },
}

// Installable agent skill (open Agent Skills standard, see skills/cookiecloud-sync/SKILL.md)
const SKILL_INSTALL_CMD = 'npx skills add easychen/CookieCloud@cookiecloud-sync'
const SKILL_SOURCE_URL = 'https://github.com/easychen/CookieCloud/blob/main/skills/cookiecloud-sync/SKILL.md'

function Nav({ t, onToggleLang }) {
  const [open, setOpen] = useState(false)
  return (
    <header className="fixed top-0 inset-x-0 z-30 backdrop-blur supports-[backdrop-filter]:bg-zinc-900/60 bg-zinc-900/80 border-b border-zinc-800">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
        <a href="#" className="flex items-center gap-2">
          <img src="/icon.png" alt="Cookie Cloud logo" className="h-6 w-6 rounded" />
          <span className="text-zinc-200 font-semibold tracking-tight">Cookie Cloud</span>
        </a>
        <nav className="hidden md:flex items-center gap-3 text-sm">
          <a className="text-zinc-300 hover:text-white" href="https://github.com/easychen/CookieCloud" target="_blank" rel="noreferrer">{t.nav.github}</a>
          <a className="text-zinc-300 hover:text-white" href="https://github.com/easychen/CookieCloud#readme" target="_blank" rel="noreferrer">{t.nav.docs}</a>
          <a className="text-zinc-300 hover:text-white" href="#agent-skill">{t.nav.agent}</a>
          <div className="relative">
            <button className="inline-flex items-center gap-1 px-3 py-1.5 rounded-md bg-zinc-800 text-zinc-200 hover:bg-zinc-700 border border-zinc-700" onClick={() => setOpen(v => !v)} aria-haspopup="menu" aria-expanded={open}>
              {t.nav.get}
            </button>
            {open && (
              <div className="absolute right-0 mt-2 w-56 rounded-md border border-zinc-700 bg-zinc-900/95 shadow-lg z-40">
                <a className="block px-3 py-2 text-zinc-200 hover:bg-zinc-800" href="https://microsoftedge.microsoft.com/addons/detail/cookiecloud/bffenpfpjikaeocaihdonmgnjjdpjkeo" target="_blank" rel="noreferrer">{t.hero.edge}</a>
                <a className="block px-3 py-2 text-zinc-200 hover:bg-zinc-800" href="https://chrome.google.com/webstore/detail/cookiecloud/ffjiejobkoibkjlhjnlgmcnnigeelbdl" target="_blank" rel="noreferrer">{t.hero.chrome}</a>
              </div>
            )}
          </div>
          <button className="px-3 py-1.5 rounded-md border border-zinc-700 bg-zinc-800 text-zinc-200 hover:bg-zinc-700" onClick={onToggleLang} aria-label="Toggle language">
            {t.nav.lang}
          </button>
        </nav>
      </div>
    </header>
  )
}

function Hero({ t }) {
  const [open, setOpen] = useState(false)
  return (
    <section className="relative pt-28">
      <div className="absolute inset-0 gradient-ring pointer-events-none" aria-hidden />
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl">
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight text-white">
            {t.hero.h1a}
            <span className="block bg-clip-text text-transparent bg-gradient-to-r from-brand to-teal-300">{t.hero.h1b}</span>
          </h1>
          <p className="mt-6 text-lg text-zinc-300">{t.hero.p}</p>
          <div className="mt-8 flex flex-wrap items-center gap-3" id="get-extension">
            <div className="relative">
              <button
                className="px-5 py-2.5 rounded-md bg-brand/90 hover:bg-brand text-zinc-950 font-medium shadow-sm"
                onClick={() => setOpen(v => !v)}
                aria-haspopup="menu"
                aria-expanded={open}
              >
                {t.hero.get}
              </button>
              {open && (
                <div className="absolute left-0 mt-2 w-64 rounded-md border border-zinc-700 bg-zinc-900/95 shadow-lg z-40">
                  <a className="block px-3 py-2 text-zinc-200 hover:bg-zinc-800" href="https://microsoftedge.microsoft.com/addons/detail/cookiecloud/bffenpfpjikaeocaihdonmgnjjdpjkeo" target="_blank" rel="noreferrer">{t.hero.edge}</a>
                  <a className="block px-3 py-2 text-zinc-200 hover:bg-zinc-800" href="https://chrome.google.com/webstore/detail/cookiecloud/ffjiejobkoibkjlhjnlgmcnnigeelbdl" target="_blank" rel="noreferrer">{t.hero.chrome}</a>
                </div>
              )}
            </div>
            <a
              className="px-5 py-2.5 rounded-md bg-zinc-800 hover:bg-zinc-700 text-zinc-200 border border-zinc-700"
              href="https://github.com/easychen/CookieCloud"
              target="_blank"
              rel="noreferrer"
            >
              {t.hero.self}
            </a>
          </div>
        </div>
      </div>
    </section>
  )
}

function Features({ t }) {
  const items = t.features

  return (
    <section className="py-16">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-6">
          {items.map((it, idx) => (
            <div key={it.title} className="hover-border-glow hover-card-gradient rounded-xl border border-zinc-800 bg-zinc-900/70 p-6">
              <div className="h-9 w-9 rounded-md bg-zinc-800 border border-zinc-700 mb-4 flex items-center justify-center text-brand">
                {idx === 0 && <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="1 4 1 10 7 10"></polyline><polyline points="23 20 23 14 17 14"></polyline><path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10"></path><path d="M3.51 15A9 9 0 0 0 18.36 18.36L23 14"></path></svg>}
                {idx === 1 && <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>}
                {idx === 2 && <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"></path></svg>}
                {idx === 3 && <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>}
                {idx === 4 && <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon></svg>}
              </div>
              <h3 className="text-zinc-100 font-semibold">{it.title}</h3>
              <p className="mt-2 text-zinc-400 text-sm leading-6">{it.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

function AgentSkill({ t }) {
  const [copied, setCopied] = useState(false)
  const [cmdCopied, setCmdCopied] = useState(false)

  const copyText = async (text) => {
    try {
      await navigator.clipboard.writeText(text)
    } catch {
      // Fallback for older browsers / non-secure contexts
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.select()
      try { document.execCommand('copy') } catch { /* noop */ }
      document.body.removeChild(ta)
    }
  }

  const copySkill = () => {
    copyText(t.skill.text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const copyInstallCmd = () => {
    copyText(SKILL_INSTALL_CMD)
    setCmdCopied(true)
    setTimeout(() => setCmdCopied(false), 2000)
  }

  return (
    <section id="agent-skill" className="py-16 scroll-mt-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl">
          <span className="text-xs font-semibold tracking-widest text-brand">{t.skill.badge}</span>
          <h2 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight text-white">{t.skill.h2}</h2>
          <p className="mt-4 text-zinc-400 leading-7">{t.skill.p}</p>
        </div>

        <div className="mt-10 grid gap-6 sm:grid-cols-3">
          {t.skill.steps.map((s, i) => (
            <div key={s.title} className="hover-border-glow hover-card-gradient rounded-xl border border-zinc-800 bg-zinc-900/70 p-6">
              <div className="flex items-center gap-3">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-brand/20 bg-brand/15 text-sm font-semibold text-brand">{i + 1}</span>
                <h3 className="text-zinc-100 font-semibold">{s.title}</h3>
              </div>
              <p className="mt-3 text-sm leading-6 text-zinc-400">{s.desc}</p>
            </div>
          ))}
        </div>

        <div className="mt-10 overflow-hidden rounded-2xl border border-zinc-700 bg-zinc-900/90">
          <div className="flex items-center justify-between gap-3 border-b border-zinc-800 px-5 py-3">
            <div className="flex items-center gap-2 text-zinc-400">
              <span className="h-2.5 w-2.5 rounded-full bg-red-400/70" aria-hidden />
              <span className="h-2.5 w-2.5 rounded-full bg-amber-400/70" aria-hidden />
              <span className="h-2.5 w-2.5 rounded-full bg-emerald-400/70" aria-hidden />
              <span className="ml-2 font-mono text-xs">cookiecloud-agent-skill.md</span>
            </div>
            <button
              onClick={copySkill}
              className={`inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium transition-colors ${
                copied ? 'bg-emerald-600 text-white' : 'bg-brand/90 text-zinc-950 hover:bg-brand'
              }`}
            >
              {copied ? t.skill.copied : t.skill.copy}
            </button>
          </div>
          <pre className="max-h-[30rem] overflow-auto whitespace-pre-wrap break-words px-5 py-4 font-mono text-[13px] leading-6 text-zinc-300">{t.skill.text}</pre>
        </div>

        <p className="mt-4 text-sm text-zinc-500">{t.skill.envNote}</p>

        <div className="mt-4 flex flex-wrap items-center gap-x-3 gap-y-2 text-sm">
          <span className="text-zinc-500">{t.skill.install}</span>
          <code className="rounded-md border border-zinc-700 bg-zinc-900 px-3 py-1.5 font-mono text-xs text-brand">{SKILL_INSTALL_CMD}</code>
          <button
            onClick={copyInstallCmd}
            className={`rounded-md px-2.5 py-1.5 text-xs font-medium transition-colors ${
              cmdCopied ? 'bg-emerald-600 text-white' : 'border border-zinc-700 bg-zinc-800 text-zinc-200 hover:bg-zinc-700'
            }`}
          >
            {cmdCopied ? t.skill.copiedCmd : t.skill.copyCmd}
          </button>
          <a className="text-zinc-400 hover:text-brand" href={SKILL_SOURCE_URL} target="_blank" rel="noreferrer">{t.skill.skillFile}</a>
        </div>
      </div>
    </section>
  )
}

function CTA({ t }) {
  return (
    <section className="py-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="rounded-2xl bg-gradient-to-br from-zinc-900 to-zinc-800 border border-zinc-700 p-8 sm:p-12">
          <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-white">{t.cta.h2}</h2>
              <p className="mt-2 text-zinc-400">{t.cta.p}</p>
            </div>
            <div className="flex gap-3">
              <a className="px-5 py-2.5 rounded-md bg-brand/90 hover:bg-brand text-zinc-950 font-medium" href="#get-extension">{t.cta.get}</a>
              <a className="px-5 py-2.5 rounded-md bg-zinc-800 hover:bg-zinc-700 text-zinc-200 border border-zinc-700" href="https://github.com/easychen/CookieCloud" target="_blank" rel="noreferrer">{t.cta.repo}</a>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function Footer({ t }) {
  return (
    <footer className="py-10 border-t border-zinc-800">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between">
        <p className="text-zinc-500 text-sm">© {new Date().getFullYear()} Cookie Cloud. {t.footer.license}.</p>
        <div className="flex items-center gap-4 text-sm">
          <a className="text-zinc-400 hover:text-zinc-200" href="https://github.com/easychen/CookieCloud" target="_blank" rel="noreferrer">GitHub</a>
          <a className="text-zinc-400 hover:text-zinc-200" href="https://github.com/easychen/CookieCloud#readme" target="_blank" rel="noreferrer">Docs</a>
          <a className="text-zinc-400 hover:text-zinc-200" href="https://github.com/easychen/CookieCloud#readme" target="_blank" rel="noreferrer">API</a>
        </div>
      </div>
    </footer>
  )
}

export default function App() {
  const [lang, setLang] = useState(() => (typeof navigator !== 'undefined' && navigator.language && navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en'))
  const t = dict[lang]
  return (
    <div className="min-h-dvh bg-zinc-950 text-zinc-200">
      <Nav t={t} onToggleLang={() => setLang(prev => (prev === 'en' ? 'zh' : 'en'))} />
      <main>
        <Hero t={t} />
        <Features t={t} />
        <AgentSkill t={t} />
        <CTA t={t} />
      </main>
      <Footer t={t} />
    </div>
  )
}